swagger: '2.0'
info:
  title: MrGreener
  description: MrGreener
  version: 1.0.0
basePath: /api/v1/
paths:
  /health:
    get:
      summary: Check status
      responses:
        200:
          description: OK
          schema:
            type: string
          examples:
            application/text:
              OK
