/**
 * MrGreener
 * Loyalty program for green initiatives
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package tech.mrgreener.application.serversidemodel

import tech.mrgreener.application.model.entities.PromotionVoucher


/**
 *
 * @param code
 * @param rewardPoints
 * @param issuedOn
 */
data class PromotionVoucher(
    val code: String,
    val reward_points: Long? = null,
    val issued_on: String? = null
) {
    constructor(promotionVoucherObj: PromotionVoucher) : this(
        promotionVoucherObj.code,
        promotionVoucherObj.rewardPoints,
        promotionVoucherObj.issuedOn.toString()
    )
}

