/**
 * MrGreener
 * Loyalty program for green initiatives
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package tech.mrgreener.application.serversidemodel

import tech.mrgreener.application.model.entities.Organization
import tech.mrgreener.application.model.entities.Promotion


/**
 *
 * @param name
 * @param priceString
 * @param descriptionShort
 * @param descriptionLong
 * @param rewardPoints
 * @param companyName
 * @param linkToStore
 * @param verified
 * @param isActive
 * @param promotionId
 * @param pictureUrl
 * @param companyAvatarUrl
 * @param whereToGet
 */
data class Promotion(
    val name: String,
//    val priceString: String,
    val description_short: String,
    val description_long: String,
    val reward_points: Long,
    val company_name: String,
    val link_to_store: String,
    val verified: Boolean,
    val is_active: Boolean,
    val promotion_id: Long? = null,
    val picture_url: String? = null,
    val company_avatar_url: String? = null,
    val where_to_get: String? = null
) {
    constructor(promotionObj: Promotion, organizationObj: Organization) : this(
        promotionObj.name,
        promotionObj.shortDescription ?: "",
        promotionObj.description,
        promotionObj.rewardPoints ?: 0,
        organizationObj.name,
        organizationObj.siteUrl ?: "",
        promotionObj.verified,
        promotionObj.isActive,
        promotionObj.id!!,
        promotionObj.pictureUrl,
        organizationObj.avatarUrl,
        organizationObj.location
    )
}

