/**
 * MrGreener
 * Loyalty program for green initiatives
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package tech.mrgreener.application.serversidemodel

import tech.mrgreener.application.model.entities.RewardVoucher


/**
 *
 * @param content
 * @param issuedOn
 */
data class RewardVoucher(
    val id: Long,
    val content: String,
    val issued_on: String
) {
    constructor(rewardVoucherObj: RewardVoucher) : this(rewardVoucherObj.id!!, rewardVoucherObj.content, rewardVoucherObj.issuedOn.toString())
}

