/**
* MrGreener
* Loyalty program for green initiatives
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tech.mrgreener.application.serversidemodel


/**
 * 
 * @param rewardPoints 
 * @param promotionId 
 */
data class VoucherRequest (
    val rewardPoints: Int,
    val promotionId: Int
) 

